// Generated by CoffeeScript 1.10.0
(function() {
  var glob, os, packageJson, path;

  path = require('path');

  os = require('os');

  glob = require('glob');

  packageJson = require('package.json');

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
